# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::431672190800:role/iamroleoidcgithub-Role-1LRMEKZ4LM1DQ
        
      - name: Instala CLI Angular
        run: npm install -g @angular/cli
      
      - name: Instala pacotes e builda o projeto
        run: |
          cd demo
          npm ci
          ng build
          ls -R dist

      - name: Copia projeto compilado para o S3
        run: |
          cd demo/dist/demo
          ls 
          aws s3 cp . s3://testegithubaction --recursive
          
